apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
    - image: airflow
      context: ./
      # enable live reload of all your dags directly into the pods dags folder
      sync:
        manual:
          - src: "dags/**/*.py"
            dest: dags
            strip: dags/
  local:
    useDockerCLI: true
deploy:
  helm:
    releases:
      - name: airflow
        chartPath: helm
        skipBuildDependencies: true
        values:
          airflow.airflow.image: airflow
        setValueTemplates:
          airflow.airflow.executor: KubernetesExecutor
          airflow.dags.persistence.enabled: false
          airflow.workers.enabled: false
          airflow.flower.enabled: false
          airflow.redis.enabled: false
          airflow.logs.persistence.enabled: true
          # ensure that also worker nodes contain dag live reload
          airflow.airflow.config.AIRFLOW__KUBERNETES__DAGS_IN_IMAGE: " True" # hack with whitespace because helm has otherwise issues with boolean values
        imageStrategy:
          helm: {}
portForward:
  - resourceType: service
    resourceName: airflow-web
    port: 8080
    localPort: 8080
